[profile.default]
out = "out"
libs = ["lib"]
remappings = ["deploy-target/=./"]
skip = ["test/echidna/**/*"]
deny = "warnings"
optimizer = true
optimizer_runs = 1000
dynamic_test_linking = false
isolate = true
gas_reports = [
  "AssetSilo",
  "AssetToken",
  "ChainlinkOracleAdapter",
  "CollateralManager",
  "CollateralManagerHarness",
  "Controller",
  "ControllerHarness",
  "CustodianModule",
  "ERC1967Proxy",
  "GoldOracleAdapter",
  "MultiCall",
  "RevenueModule",
  "StakedAsset",
  "StakedAssetHarness",
  "SwapModule",
  "SwapModuleHarness"
]
fs_permissions = [{ access = "read-write", path = "./" }]

# compile production contracts with via-ir
[profile.production]
src = "src"
skip = ["test/**/*"]
remappings = ["deploy-target/=./"]
via_ir = true
ffi = true
optimizer = true
optimizer_runs = 18888

[profile.development]
src = "src"
skip = ["test/**/*"]
remappings = ["deploy-target/=./"]
via_ir = true
ffi = true
optimizer = true
optimizer_runs = 18888

[profile.production-test]
remappings = ["deploy-target/=./"]
via_ir = true
ffi = true
optimizer = true
optimizer_runs = 18888

[profile.development-test]
remappings = ["deploy-target/=."]
src = "src"
optimizer = true
optimizer_runs = 1000

[profile.echidna]
remappings = ["deploy-target/=."]
skip = ["script/**", "test/fork/**", "test/integration/**", "test/harness/**"]
src = "src"
optimizer = true
optimizer_runs = 1000

[lint]
ignore = ["test/external/**/*", "test/echidna/**/*"]
exclude_lints = [
  "mixed-case-variable",
  "screaming-snake-case-immutable",
  "asm-keccak256",
  "unwrapped-modifier-logic",
  "block-timestamp"
]

[fuzz]
runs = 5000

[profile.coverage]
skip = [
  "test/echidna/*",
  "test/external/*",
  "test/fork/*",
  "test/integration/*",
  "test/invariant/*", 
  "test/mocks/*", 
  "script/*"
]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
dstSepolia = "${RPC_URL_ARBITRUM_SEPOLIA}"

[invariant]
runs = 444
depth = 50
fail_on_revert = false
