#!/usr/bin/env python3
"""Generate test/echidna/mainnet/MainnetAddresses.sol from deployments.json.

Echidna runs on hevm, which has no `vm.readFile` / `vm.parseJson`, so mainnet
harnesses cannot read deployments.json the way test/fork/monitoring/MonitorBase.sol
does. Addresses are baked in as constants instead, and CI re-runs this script and
diffs the result to catch drift after a redeploy.

Usage: python3 script/gen_mainnet_addresses.py [--check]
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEPLOYMENTS = ROOT / "deployments.json"
OUTPUT = ROOT / "test/echidna/mainnet/MainnetAddresses.sol"

ASSETS = ["tGLD", "tBRL", "tMXN"]

# Order matters only for output stability; taken from MonitorBase.DeployedContracts.
CONTRACT_KEYS = [
    "asset_token",
    "collateral",
    "collateral_manager",
    "controller",
    "custodian_module",
    "multicall",
    "oracle_adapter",
    "revenue_module",
    "silo",
    "staked_asset",
    "swap_module",
]

HEADER = """// SPDX-License-Identifier: MIT
pragma solidity 0.8.30;

// AUTOGENERATED by script/gen_mainnet_addresses.py from deployments.json -- DO NOT EDIT.
// Regenerate with: python3 script/gen_mainnet_addresses.py

/// @notice Live mainnet addresses, baked in as constants because hevm (Echidna)
/// supports neither `vm.readFile` nor `vm.parseJson`.
library MainnetAddresses {
"""


def const_name(asset: str, key: str) -> str:
    return f"{asset.upper()}_{key.upper()}"


def role_fn_name(asset: str, role: str) -> str:
    parts = role.split("_")
    camel = parts[0] + "".join(p.capitalize() for p in parts[1:])
    return f"{asset}_{camel}"


def render(deployments: dict) -> str:
    mainnet = deployments["mainnet"]
    out = [HEADER]

    for asset in ASSETS:
        entry = mainnet[asset]
        out.append(f"    // ---------------- {asset} ----------------\n")
        for key in CONTRACT_KEYS:
            addr = entry["contracts"][key]
            out.append(f"    address internal constant {const_name(asset, key)} = {addr};\n")

        vault = entry.get("vault", {}).get("contracts", {})
        for key in sorted(vault):
            out.append(
                f"    address internal constant {const_name(asset, 'VAULT_' + key)} = {vault[key]};\n"
            )
        out.append("\n")

    # Role holders as functions -- Solidity has no constant address[].
    for asset in ASSETS:
        roles = mainnet[asset]["roles"]
        for role in sorted(roles):
            holders = roles[role]
            out.append(
                f"    /// @notice {asset} {role} holders as of the last deployments.json update\n"
            )
            out.append(
                f"    function {role_fn_name(asset, role)}() internal pure "
                f"returns (address[] memory holders) {{\n"
            )
            out.append(f"        holders = new address[]({len(holders)});\n")
            for i, holder in enumerate(holders):
                out.append(f"        holders[{i}] = {holder};\n")
            out.append("    }\n\n")

    # Drop the trailing blank line before `}` to satisfy `forge fmt --check`.
    if out[-1].endswith("\n\n"):
        out[-1] = out[-1][:-1]
    out.append("}\n")
    return "".join(out)


def main() -> int:
    deployments = json.loads(DEPLOYMENTS.read_text())
    rendered = render(deployments)

    if "--check" in sys.argv:
        if not OUTPUT.exists():
            print(f"{OUTPUT} missing; run: python3 script/gen_mainnet_addresses.py")
            return 1
        if OUTPUT.read_text() != rendered:
            print(f"{OUTPUT} is stale; run: python3 script/gen_mainnet_addresses.py")
            return 1
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered)
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
