// SPDX-License-Identifier: MIT
pragma solidity 0.8.30;

// AUTOGENERATED by script/gen_mainnet_addresses.py from deployments.json -- DO NOT EDIT.
// Regenerate with: python3 script/gen_mainnet_addresses.py

/// @notice Live mainnet addresses, baked in as constants because hevm (Echidna)
/// supports neither `vm.readFile` nor `vm.parseJson`.
library MainnetAddresses {
    // ---------------- tGLD ----------------
    address internal constant TGLD_ASSET_TOKEN = 0x6a547b25534234bb79CE6961a23Db13DE154b6F4;
    address internal constant TGLD_COLLATERAL = 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48;
    address internal constant TGLD_COLLATERAL_MANAGER = 0x42F3F01D45E67294e20cE98AcFDC24dD7EA75dEa;
    address internal constant TGLD_CONTROLLER = 0x5e631388b24ec493619DAEEAef6fc34B33d97Dcd;
    address internal constant TGLD_CUSTODIAN_MODULE = 0x97e1C8dc9a3CcA064fAA8318f9b5C7AdB26b0e89;
    address internal constant TGLD_MULTICALL = 0xdA8B85Cd62CDB3C104c80b479f9094e07EBcF7e8;
    address internal constant TGLD_ORACLE_ADAPTER = 0x0977592F86616788Fd809446E094F9Bb91E97A44;
    address internal constant TGLD_REVENUE_MODULE = 0x933745Dc6fcBcCDc491d9A8322672d731C8a262e;
    address internal constant TGLD_SILO = 0x572cE2dfdDF795b1332d592b585Ae17E492E4b41;
    address internal constant TGLD_STAKED_ASSET = 0x8d301801d899dC81fEabBDE69407A53b82bdBF19;
    address internal constant TGLD_SWAP_MODULE = 0xB426bcB6028Ba1fBB746a8af11859D97007BE594;
    address internal constant TGLD_VAULT_GATE = 0x70056E107dFBb58B74739Ba095E1Dd77CCC7cab1;
    address internal constant TGLD_VAULT_VAULT = 0x7290245b3e564f0Ae2dA5af0690eF4842CF13c75;

    // ---------------- tBRL ----------------
    address internal constant TBRL_ASSET_TOKEN = 0x4C1b46adb8877E389171EC6Ef67b385094C0afaD;
    address internal constant TBRL_COLLATERAL = 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48;
    address internal constant TBRL_COLLATERAL_MANAGER = 0x67eB9338bAd71443aDC1f6C319D5400292a8b7e4;
    address internal constant TBRL_CONTROLLER = 0x0EF47CC8E244dBc8628FdEfFD4EE4DD747d14081;
    address internal constant TBRL_CUSTODIAN_MODULE = 0xfb3C3d52a60aea06064B13833dD730F18c61cB29;
    address internal constant TBRL_MULTICALL = 0x5399170161aF5f8f769Cb6B185034579A00c8765;
    address internal constant TBRL_ORACLE_ADAPTER = 0xDfD57C54F970910dCcc843d37EE0B84E45b62a06;
    address internal constant TBRL_REVENUE_MODULE = 0x83cF329b9cbD2790aB2002E880592358C7c8Ff5F;
    address internal constant TBRL_SILO = 0xE6dF42C4B7A38A17e5A831D7Ec443bc949D33b31;
    address internal constant TBRL_STAKED_ASSET = 0xDaB276F6E19CCC54cA5aaA2645A94087ca776a3f;
    address internal constant TBRL_SWAP_MODULE = 0xe4f4Ff36055e9FffACB81be65B241CDe356bB0e4;
    address internal constant TBRL_VAULT_GATE = 0xCF57CB92E0af71C1E3A2918e3FEe77D062f2E663;
    address internal constant TBRL_VAULT_VAULT = 0xE275a69B93A5745e1560ee82D033205D323BfAd9;

    // ---------------- tMXN ----------------
    address internal constant TMXN_ASSET_TOKEN = 0x8d015aFcb6F437010653352EB1E58152c4e23734;
    address internal constant TMXN_COLLATERAL = 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48;
    address internal constant TMXN_COLLATERAL_MANAGER = 0x2a21014B89F72de3Ffa6d645F89b8Ca5A6eFfe75;
    address internal constant TMXN_CONTROLLER = 0xB5EBDeC6DA02119DD7BEB4782C181261f8BfEcC2;
    address internal constant TMXN_CUSTODIAN_MODULE = 0xb6CE19EC436a4ea57E0196973f65eF47353fA674;
    address internal constant TMXN_MULTICALL = 0xbE4b8f1cEb7710F896c963b0452335394eFAC166;
    address internal constant TMXN_ORACLE_ADAPTER = 0xb5c72C24794bbcc2cab1773b7fE05C77194F7273;
    address internal constant TMXN_REVENUE_MODULE = 0xD7D6C0c722b918045F1D725C5BB09F79Fc851033;
    address internal constant TMXN_SILO = 0x997ba5538fE0C0b6acb10fF2Ba71Ab0b3E66f63F;
    address internal constant TMXN_STAKED_ASSET = 0x8BDf6A2DFda084bD242Cd285CF75E80de3eB00ba;
    address internal constant TMXN_SWAP_MODULE = 0xC274d87c8Ed44d85A1b0975a82a41e55eB891d86;
    address internal constant TMXN_VAULT_GATE = 0x0C4D7b141479b93826b27e5D81b86f5E9B52B136;
    address internal constant TMXN_VAULT_VAULT = 0x43E3f5e27422C3a938269368eb7c3A3B545Bb6ca;

    /// @notice tGLD admin_role holders as of the last deployments.json update
    function tGLD_adminRole() internal pure returns (address[] memory holders) {
        holders = new address[](1);
        holders[0] = 0xE6Eb534f33A635e8d867414Af32F766D221F30d1;
    }

    /// @notice tGLD cap_adjuster_role holders as of the last deployments.json update
    function tGLD_capAdjusterRole() internal pure returns (address[] memory holders) {
        holders = new address[](1);
        holders[0] = 0x48Fa008bD2660974d55Ee9b7A9ECA1cE61347614;
    }

    /// @notice tGLD curator_role holders as of the last deployments.json update
    function tGLD_curatorRole() internal pure returns (address[] memory holders) {
        holders = new address[](3);
        holders[0] = 0xD1a89086428E2b208414201712cbE0952DabEA03;
        holders[1] = 0xdA8B85Cd62CDB3C104c80b479f9094e07EBcF7e8;
        holders[2] = 0x5e631388b24ec493619DAEEAef6fc34B33d97Dcd;
    }

    /// @notice tGLD custodian_keeper_role holders as of the last deployments.json update
    function tGLD_custodianKeeperRole() internal pure returns (address[] memory holders) {
        holders = new address[](1);
        holders[0] = 0xD1a89086428E2b208414201712cbE0952DabEA03;
    }

    /// @notice tGLD default_admin_role holders as of the last deployments.json update
    function tGLD_defaultAdminRole() internal pure returns (address[] memory holders) {
        holders = new address[](1);
        holders[0] = 0x698c6d3726846C4AD4Dc9331862b92Cd80D2fb99;
    }

    /// @notice tGLD gatekeeper_role holders as of the last deployments.json update
    function tGLD_gatekeeperRole() internal pure returns (address[] memory holders) {
        holders = new address[](2);
        holders[0] = 0x44C24D0937A829B3057be462b0e069516f1D9D45;
        holders[1] = 0xE6Eb534f33A635e8d867414Af32F766D221F30d1;
    }

    /// @notice tGLD minter_role holders as of the last deployments.json update
    function tGLD_minterRole() internal pure returns (address[] memory holders) {
        holders = new address[](2);
        holders[0] = 0xCa2D7CfAa96290171c98e112c73fC87c2AE2fe9B;
        holders[1] = 0xdA8B85Cd62CDB3C104c80b479f9094e07EBcF7e8;
    }

    /// @notice tGLD multicaller_role holders as of the last deployments.json update
    function tGLD_multicallerRole() internal pure returns (address[] memory holders) {
        holders = new address[](1);
        holders[0] = 0xCa2D7CfAa96290171c98e112c73fC87c2AE2fe9B;
    }

    /// @notice tGLD rebalancer_role holders as of the last deployments.json update
    function tGLD_rebalancerRole() internal pure returns (address[] memory holders) {
        holders = new address[](1);
        holders[0] = 0xD1a89086428E2b208414201712cbE0952DabEA03;
    }

    /// @notice tGLD restricter_role holders as of the last deployments.json update
    function tGLD_restricterRole() internal pure returns (address[] memory holders) {
        holders = new address[](1);
        holders[0] = 0xE6Eb534f33A635e8d867414Af32F766D221F30d1;
    }

    /// @notice tGLD revenue_keeper_role holders as of the last deployments.json update
    function tGLD_revenueKeeperRole() internal pure returns (address[] memory holders) {
        holders = new address[](1);
        holders[0] = 0xD1a89086428E2b208414201712cbE0952DabEA03;
    }

    /// @notice tGLD rewarder_role holders as of the last deployments.json update
    function tGLD_rewarderRole() internal pure returns (address[] memory holders) {
        holders = new address[](2);
        holders[0] = 0x933745Dc6fcBcCDc491d9A8322672d731C8a262e;
        holders[1] = 0x9cC553d9F9e9690C0bc97bC2E1d10696d3862aC8;
    }

    /// @notice tGLD signer_manager_role holders as of the last deployments.json update
    function tGLD_signerManagerRole() internal pure returns (address[] memory holders) {
        holders = new address[](1);
        holders[0] = 0x48Fa008bD2660974d55Ee9b7A9ECA1cE61347614;
    }

    /// @notice tBRL admin_role holders as of the last deployments.json update
    function tBRL_adminRole() internal pure returns (address[] memory holders) {
        holders = new address[](1);
        holders[0] = 0xE6Eb534f33A635e8d867414Af32F766D221F30d1;
    }

    /// @notice tBRL cap_adjuster_role holders as of the last deployments.json update
    function tBRL_capAdjusterRole() internal pure returns (address[] memory holders) {
        holders = new address[](1);
        holders[0] = 0x48Fa008bD2660974d55Ee9b7A9ECA1cE61347614;
    }

    /// @notice tBRL curator_role holders as of the last deployments.json update
    function tBRL_curatorRole() internal pure returns (address[] memory holders) {
        holders = new address[](1);
        holders[0] = 0xdAA880D1BdF3fB04B760235D0a4B384F2c403A43;
    }

    /// @notice tBRL custodian_keeper_role holders as of the last deployments.json update
    function tBRL_custodianKeeperRole() internal pure returns (address[] memory holders) {
        holders = new address[](1);
        holders[0] = 0xdAA880D1BdF3fB04B760235D0a4B384F2c403A43;
    }

    /// @notice tBRL default_admin_role holders as of the last deployments.json update
    function tBRL_defaultAdminRole() internal pure returns (address[] memory holders) {
        holders = new address[](1);
        holders[0] = 0x698c6d3726846C4AD4Dc9331862b92Cd80D2fb99;
    }

    /// @notice tBRL gatekeeper_role holders as of the last deployments.json update
    function tBRL_gatekeeperRole() internal pure returns (address[] memory holders) {
        holders = new address[](2);
        holders[0] = 0x9A4441238fc27d9f1c5Ae3E05E6517b0389FB513;
        holders[1] = 0xE6Eb534f33A635e8d867414Af32F766D221F30d1;
    }

    /// @notice tBRL minter_role holders as of the last deployments.json update
    function tBRL_minterRole() internal pure returns (address[] memory holders) {
        holders = new address[](2);
        holders[0] = 0xcC5e557169033933c99A2Ade24092F4297797f98;
        holders[1] = 0x5399170161aF5f8f769Cb6B185034579A00c8765;
    }

    /// @notice tBRL multicaller_role holders as of the last deployments.json update
    function tBRL_multicallerRole() internal pure returns (address[] memory holders) {
        holders = new address[](1);
        holders[0] = 0xcC5e557169033933c99A2Ade24092F4297797f98;
    }

    /// @notice tBRL rebalancer_role holders as of the last deployments.json update
    function tBRL_rebalancerRole() internal pure returns (address[] memory holders) {
        holders = new address[](1);
        holders[0] = 0xdAA880D1BdF3fB04B760235D0a4B384F2c403A43;
    }

    /// @notice tBRL restricter_role holders as of the last deployments.json update
    function tBRL_restricterRole() internal pure returns (address[] memory holders) {
        holders = new address[](1);
        holders[0] = 0xE6Eb534f33A635e8d867414Af32F766D221F30d1;
    }

    /// @notice tBRL revenue_keeper_role holders as of the last deployments.json update
    function tBRL_revenueKeeperRole() internal pure returns (address[] memory holders) {
        holders = new address[](1);
        holders[0] = 0xdAA880D1BdF3fB04B760235D0a4B384F2c403A43;
    }

    /// @notice tBRL rewarder_role holders as of the last deployments.json update
    function tBRL_rewarderRole() internal pure returns (address[] memory holders) {
        holders = new address[](2);
        holders[0] = 0x9cC553d9F9e9690C0bc97bC2E1d10696d3862aC8;
        holders[1] = 0x83cF329b9cbD2790aB2002E880592358C7c8Ff5F;
    }

    /// @notice tBRL signer_manager_role holders as of the last deployments.json update
    function tBRL_signerManagerRole() internal pure returns (address[] memory holders) {
        holders = new address[](1);
        holders[0] = 0x48Fa008bD2660974d55Ee9b7A9ECA1cE61347614;
    }

    /// @notice tMXN admin_role holders as of the last deployments.json update
    function tMXN_adminRole() internal pure returns (address[] memory holders) {
        holders = new address[](1);
        holders[0] = 0xE6Eb534f33A635e8d867414Af32F766D221F30d1;
    }

    /// @notice tMXN cap_adjuster_role holders as of the last deployments.json update
    function tMXN_capAdjusterRole() internal pure returns (address[] memory holders) {
        holders = new address[](1);
        holders[0] = 0x48Fa008bD2660974d55Ee9b7A9ECA1cE61347614;
    }

    /// @notice tMXN curator_role holders as of the last deployments.json update
    function tMXN_curatorRole() internal pure returns (address[] memory holders) {
        holders = new address[](1);
        holders[0] = 0xB6BA562eF547c94C2A863D5e4E0395695CfCF714;
    }

    /// @notice tMXN custodian_keeper_role holders as of the last deployments.json update
    function tMXN_custodianKeeperRole() internal pure returns (address[] memory holders) {
        holders = new address[](1);
        holders[0] = 0xB6BA562eF547c94C2A863D5e4E0395695CfCF714;
    }

    /// @notice tMXN default_admin_role holders as of the last deployments.json update
    function tMXN_defaultAdminRole() internal pure returns (address[] memory holders) {
        holders = new address[](1);
        holders[0] = 0x698c6d3726846C4AD4Dc9331862b92Cd80D2fb99;
    }

    /// @notice tMXN gatekeeper_role holders as of the last deployments.json update
    function tMXN_gatekeeperRole() internal pure returns (address[] memory holders) {
        holders = new address[](2);
        holders[0] = 0xa1B49D8597CeC8C7f26B551C825D3F864c14d32c;
        holders[1] = 0xE6Eb534f33A635e8d867414Af32F766D221F30d1;
    }

    /// @notice tMXN minter_role holders as of the last deployments.json update
    function tMXN_minterRole() internal pure returns (address[] memory holders) {
        holders = new address[](2);
        holders[0] = 0x1B24074Ceb5d4A911E9eFf77c90601C12b98A8be;
        holders[1] = 0xbE4b8f1cEb7710F896c963b0452335394eFAC166;
    }

    /// @notice tMXN multicaller_role holders as of the last deployments.json update
    function tMXN_multicallerRole() internal pure returns (address[] memory holders) {
        holders = new address[](1);
        holders[0] = 0x1B24074Ceb5d4A911E9eFf77c90601C12b98A8be;
    }

    /// @notice tMXN rebalancer_role holders as of the last deployments.json update
    function tMXN_rebalancerRole() internal pure returns (address[] memory holders) {
        holders = new address[](1);
        holders[0] = 0xB6BA562eF547c94C2A863D5e4E0395695CfCF714;
    }

    /// @notice tMXN restricter_role holders as of the last deployments.json update
    function tMXN_restricterRole() internal pure returns (address[] memory holders) {
        holders = new address[](1);
        holders[0] = 0xE6Eb534f33A635e8d867414Af32F766D221F30d1;
    }

    /// @notice tMXN revenue_keeper_role holders as of the last deployments.json update
    function tMXN_revenueKeeperRole() internal pure returns (address[] memory holders) {
        holders = new address[](1);
        holders[0] = 0xB6BA562eF547c94C2A863D5e4E0395695CfCF714;
    }

    /// @notice tMXN rewarder_role holders as of the last deployments.json update
    function tMXN_rewarderRole() internal pure returns (address[] memory holders) {
        holders = new address[](2);
        holders[0] = 0x9cC553d9F9e9690C0bc97bC2E1d10696d3862aC8;
        holders[1] = 0xD7D6C0c722b918045F1D725C5BB09F79Fc851033;
    }

    /// @notice tMXN signer_manager_role holders as of the last deployments.json update
    function tMXN_signerManagerRole() internal pure returns (address[] memory holders) {
        holders = new address[](1);
        holders[0] = 0x48Fa008bD2660974d55Ee9b7A9ECA1cE61347614;
    }
}
