name: Tenbin Contracts

permissions: {}

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci
  MAINNET_RPC_URL: ${{ secrets.MAINNET_FORK_URL }}
  SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_FORK_URL }}
  RPC_URL_ARBITRUM_SEPOLIA: ${{ secrets.RPC_URL_ARBITRUM_SEPOLIA }}
  TEST_MNEMONIC: ${{ secrets.TEST_MNEMONIC }}

jobs:
  check:
    name: Tenbin project
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: false
          fetch-depth: 1

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          cache: true

      - name: Run Forge build
        run: forge build

      - name: Run Forge tests
        run: forge test -vvv