name: Tenbin Contracts

permissions: {}

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci
  MAINNET_RPC_URL: ${{ secrets.MAINNET_FORK_URL }}
  TEST_MNEMONIC: ${{ secrets.TEST_MNEMONIC }}

jobs:
  check:
    name: Tenbin project
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run Forge build
        run: forge build

      - name: Run Forge tests
        run: forge test -vvv